name: Construir APK Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- NUEVO PASO OBLIGATORIO ---
      - name: Configurar Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      # ------------------------------

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar dependencias
        run: cd movilizate-ionic && npm install

      - name: Instalar Ionic CLI Global
        run: npm install -g @ionic/cli

      - name: Construir Web (Modo Inteligente)
        run: cd movilizate-ionic && ionic build --prod

      - name: Preparar Android
        run: |
          cd movilizate-ionic
          npm install @capacitor/android
          npx cap add android || true
          npx cap sync

      - name: Construir APK
        run: cd movilizate-ionic/android && chmod +x gradlew && ./gradlew assembleDebug

      - name: Subir APK a GitHub
        uses: actions/upload-artifact@v4
        with:
          name: APP-MOVILIZATE-ANDROID
          path: movilizate-ionic/android/app/build/outputs/apk/debug/app-debug.apk
